// Generated by cpp11: do not edit by hand
// clang-format off

#include "opensimplex2_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// simplex2r.cpp
doubles_matrix<> noise2d_(int width, int height, double frequency);
extern "C" SEXP _opensimplex2_noise2d_(SEXP width, SEXP height, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise2d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
sexp noise3d_(int width, int height, int depth, double frequency);
extern "C" SEXP _opensimplex2_noise3d_(SEXP width, SEXP height, SEXP depth, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise3d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
sexp noise4d_(int width, int height, int depth, int slice, double frequency);
extern "C" SEXP _opensimplex2_noise4d_(SEXP width, SEXP height, SEXP depth, SEXP slice, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise4d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(slice), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
doubles_matrix<> noise2dS_(int width, int height, double frequency);
extern "C" SEXP _opensimplex2_noise2dS_(SEXP width, SEXP height, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise2dS_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
sexp noise3dS_(int width, int height, int depth, double frequency);
extern "C" SEXP _opensimplex2_noise3dS_(SEXP width, SEXP height, SEXP depth, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise3dS_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
sexp noise4dS_(int width, int height, int depth, int slice, double frequency);
extern "C" SEXP _opensimplex2_noise4dS_(SEXP width, SEXP height, SEXP depth, SEXP slice, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise4dS_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(slice), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// simplex2r.cpp
external_pointer<SimplexSpace> simplex_space_(std::string type, int dimensions);
extern "C" SEXP _opensimplex2_simplex_space_(SEXP type, SEXP dimensions) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_space_(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<int>>(dimensions)));
  END_CPP11
}
// simplex2r.cpp
sexp simplex_sample_space_2d(external_pointer<SimplexSpace> ss, doubles i, doubles j);
extern "C" SEXP _opensimplex2_simplex_sample_space_2d(SEXP ss, SEXP i, SEXP j) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_sample_space_2d(cpp11::as_cpp<cpp11::decay_t<external_pointer<SimplexSpace>>>(ss), cpp11::as_cpp<cpp11::decay_t<doubles>>(i), cpp11::as_cpp<cpp11::decay_t<doubles>>(j)));
  END_CPP11
}
// simplex2r.cpp
sexp simplex_sample_space_3d(external_pointer<SimplexSpace> ss, doubles i, doubles j, doubles k);
extern "C" SEXP _opensimplex2_simplex_sample_space_3d(SEXP ss, SEXP i, SEXP j, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_sample_space_3d(cpp11::as_cpp<cpp11::decay_t<external_pointer<SimplexSpace>>>(ss), cpp11::as_cpp<cpp11::decay_t<doubles>>(i), cpp11::as_cpp<cpp11::decay_t<doubles>>(j), cpp11::as_cpp<cpp11::decay_t<doubles>>(k)));
  END_CPP11
}
// simplex2r.cpp
sexp simplex_sample_space_4d(external_pointer<SimplexSpace> ss, doubles i, doubles j, doubles k, doubles l);
extern "C" SEXP _opensimplex2_simplex_sample_space_4d(SEXP ss, SEXP i, SEXP j, SEXP k, SEXP l) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_sample_space_4d(cpp11::as_cpp<cpp11::decay_t<external_pointer<SimplexSpace>>>(ss), cpp11::as_cpp<cpp11::decay_t<doubles>>(i), cpp11::as_cpp<cpp11::decay_t<doubles>>(j), cpp11::as_cpp<cpp11::decay_t<doubles>>(k), cpp11::as_cpp<cpp11::decay_t<doubles>>(l)));
  END_CPP11
}
// simplex2r.cpp
sexp simplex_sample_close(external_pointer<SimplexSpace> ss);
extern "C" SEXP _opensimplex2_simplex_sample_close(SEXP ss) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_sample_close(cpp11::as_cpp<cpp11::decay_t<external_pointer<SimplexSpace>>>(ss)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_opensimplex2_noise2dS_",               (DL_FUNC) &_opensimplex2_noise2dS_,               3},
    {"_opensimplex2_noise2d_",                (DL_FUNC) &_opensimplex2_noise2d_,                3},
    {"_opensimplex2_noise3dS_",               (DL_FUNC) &_opensimplex2_noise3dS_,               4},
    {"_opensimplex2_noise3d_",                (DL_FUNC) &_opensimplex2_noise3d_,                4},
    {"_opensimplex2_noise4dS_",               (DL_FUNC) &_opensimplex2_noise4dS_,               5},
    {"_opensimplex2_noise4d_",                (DL_FUNC) &_opensimplex2_noise4d_,                5},
    {"_opensimplex2_simplex_sample_close",    (DL_FUNC) &_opensimplex2_simplex_sample_close,    1},
    {"_opensimplex2_simplex_sample_space_2d", (DL_FUNC) &_opensimplex2_simplex_sample_space_2d, 3},
    {"_opensimplex2_simplex_sample_space_3d", (DL_FUNC) &_opensimplex2_simplex_sample_space_3d, 4},
    {"_opensimplex2_simplex_sample_space_4d", (DL_FUNC) &_opensimplex2_simplex_sample_space_4d, 5},
    {"_opensimplex2_simplex_space_",          (DL_FUNC) &_opensimplex2_simplex_space_,          2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_opensimplex2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
