// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
doubles_matrix<> noise2d_(int width, int height, double frequency);
extern "C" SEXP _opensimplex2_noise2d_(SEXP width, SEXP height, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise2d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// code.cpp
sexp noise3d_(int width, int height, int depth, double frequency);
extern "C" SEXP _opensimplex2_noise3d_(SEXP width, SEXP height, SEXP depth, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise3d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}
// code.cpp
sexp noise4d_(int width, int height, int depth, int slice, double frequency);
extern "C" SEXP _opensimplex2_noise4d_(SEXP width, SEXP height, SEXP depth, SEXP slice, SEXP frequency) {
  BEGIN_CPP11
    return cpp11::as_sexp(noise4d_(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(slice), cpp11::as_cpp<cpp11::decay_t<double>>(frequency)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_opensimplex2_noise2d_", (DL_FUNC) &_opensimplex2_noise2d_, 3},
    {"_opensimplex2_noise3d_", (DL_FUNC) &_opensimplex2_noise3d_, 4},
    {"_opensimplex2_noise4d_", (DL_FUNC) &_opensimplex2_noise4d_, 5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_opensimplex2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
