# Generated by cpp11: do not edit by hand

noise2d_ <- function(width, height, frequency) {
  .Call(`_opensimplex2_noise2d_`, width, height, frequency)
}

noise3d_ <- function(width, height, depth, frequency) {
  .Call(`_opensimplex2_noise3d_`, width, height, depth, frequency)
}

noise4d_ <- function(width, height, depth, slice, frequency) {
  .Call(`_opensimplex2_noise4d_`, width, height, depth, slice, frequency)
}

noise2dS_ <- function(width, height, frequency) {
  .Call(`_opensimplex2_noise2dS_`, width, height, frequency)
}

noise3dS_ <- function(width, height, depth, frequency) {
  .Call(`_opensimplex2_noise3dS_`, width, height, depth, frequency)
}

noise4dS_ <- function(width, height, depth, slice, frequency) {
  .Call(`_opensimplex2_noise4dS_`, width, height, depth, slice, frequency)
}
