# Generated by cpp11: do not edit by hand

noise2d_ <- function(width, height, frequency) {
  .Call(`_opensimplex2_noise2d_`, width, height, frequency)
}

noise3d_ <- function(width, height, depth, frequency) {
  .Call(`_opensimplex2_noise3d_`, width, height, depth, frequency)
}

noise4d_ <- function(width, height, depth, slice, frequency) {
  .Call(`_opensimplex2_noise4d_`, width, height, depth, slice, frequency)
}

noise2dS_ <- function(width, height, frequency) {
  .Call(`_opensimplex2_noise2dS_`, width, height, frequency)
}

noise3dS_ <- function(width, height, depth, frequency) {
  .Call(`_opensimplex2_noise3dS_`, width, height, depth, frequency)
}

noise4dS_ <- function(width, height, depth, slice, frequency) {
  .Call(`_opensimplex2_noise4dS_`, width, height, depth, slice, frequency)
}

simplex_space_ <- function(type, dimensions) {
  .Call(`_opensimplex2_simplex_space_`, type, dimensions)
}

simplex_sample_space_2d <- function(ss, i, j) {
  .Call(`_opensimplex2_simplex_sample_space_2d`, ss, i, j)
}

simplex_sample_space_3d <- function(ss, i, j, k) {
  .Call(`_opensimplex2_simplex_sample_space_3d`, ss, i, j, k)
}

simplex_sample_space_4d <- function(ss, i, j, k, l) {
  .Call(`_opensimplex2_simplex_sample_space_4d`, ss, i, j, k, l)
}

simplex_sample_close <- function(ss) {
  .Call(`_opensimplex2_simplex_sample_close`, ss)
}
